### PR TITLE
Workflow to Update latest SHAs for images into a location

### PR DESCRIPTION
**Pull request by rpancham**
Task involves enhancing the workflow to include a method for retrieving and listing the latest SHA for an image. This list of SHAs can be used later for various purposes, such as updating the image SHAs at the end of a sprint.

Issue : [RHOAIENG-9158](https://issues.redhat.com/browse/RHOAIENG-9158)

### CODE REVIEW

**Comment by rpancham** [comment]
This is how the output looks like 
[Get Image SHAs from Quay.io · rpancham_automate-release@5e81d14.pdf](https://github.com/user-attachments/files/16313440/Get.Image.SHAs.from.Quay.io.rpancham_automate-release%405e81d14.pdf)




image

**Review by Xaenalt — CHANGES_REQUESTED** [review]
First off, excellent, this is great for getting a single repo!

There's two changes we need to make:
1. We need to be able to get the SHA for a given tag from multiple repos
2. In the case where a tag doesn't exist for a repo, that's fine we can just print that out in the output

The intent of this workflow is to make updating files like https://github.com/red-hat-data-services/odh-model-controller/blob/rhoai-2.11/config/base/params.env easier by having a single workflow that can retrieve all the SHAs. If they haven't finished a build yet, we can simply inspect the output and see the tag doesn't exist and inspect the status manually for now

**Comment by rpancham** [comment]
Output :

If Tag is not present 
https://github.com/rpancham/automate-release/actions/runs/10093775225

If Tag is Present in all the repo
https://github.com/rpancham/automate-release/actions/runs/10093402660

**Review by Xaenalt — APPROVED** [review]
Hell yeah, awesome work!

**Comment by spolti** [comment]
very nice, can we have it for the server & metrics components as well?

**Comment by rpancham** [comment]
> very nice, can we have it for the server & metrics components as well?

Yes @spolti you can have it in Server and Metrics components as well, you can use the existing code .

**Pull request merged**
